### ISSUE TITLE
Change name of this repository - API, not Api

### ISSUE THREAD

**Issue by inson1** [OhMyGuus/I-Still-Dont-Care-About-Cookies-Api#7]
Because of #6, plus that's how it's spelled

**Comment by obfuscated-loop** [comment]
I'm pretty sure the reason why it is not uppercase is because that is the C# standard. For instance, take this import as an example:
```csharp
using System.Text.Json.Serialization;
```

**Comment by OhMyGuus** [comment]
Api is the correct naming convention for namespaces, project names in c#
